
parameters {
   string(name: 'modules', defaultValue: '', description: 'Modules to Build')
}
modules = "${params.modules}".split(':')
versionNr  = "${params.versionNr}"
releaseNr  = "${params.releaseNr}"
installTarget  = "${params.installTarget}"

pipeline {
    agent any
       stages {
          stage('Maven Builds') {
              steps {
                check_out_service(servicename, "xyz")
                newrevision&publishBom(servicename,  "xyz")
                maven_build(modules)
                saverevision()
              }
        }
     }
}


def maven_build(list) {
    list.each { module ->
        dir("${module}") {
            sh "mvn clean install"
         }
    }
}
