
parameters {
    string(name: 'TARGET', defaultValue: 'CHEI212', description: 'Installations Target')
    string(name: 'VERSION', defaultValue: '0.1-SNAPSHOT', description: 'Version Nummer')
    string(name: 'SERVICENAME', defaultValue: 'echoservice', description: 'Name of Service')
    string(name: 'TARGETHOST', defaultValue: 'jades-e.apgsga.ch', description: 'DSN Name of Targethost')
    string(name: 'REPO' , defaultValue: 'https://github.com/apgsga-it/apg-gradle-plugins.git', description: 'VCS Repo of module')
    string(name: 'MODULE' , defaultValue: 'testapp-pkg', description: 'Build directory')
    string(name: 'BRANCH' , defaultValue: 'master', description: 'Branch of Module')
    
}

stage("Build and Install ${params.SERVICENAME} for ${params.TARGET} on ${params.TARGETHOST}") {
 node {
		checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: "${params.BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${params.REPO}"]]]        
		echo "Changing Directory to ${params.MODULE}"
		dir "${params.MODULE}"
		echo "Changing Directory to ${params.MODULE}"
		def cmd = "chmod +x ./gradlew"
		echo "Executing shell command ${cmd}"
        sh "${cmd}"  
        echo "Executing shell command ${cmd} done"  
        echo "About to withCredentials"
    	withCredentials([usernamePassword(credentialsId:'jadas-e-ssh', passwordVariable: 'passwd', usernameVariable: 'username')])   { 
            sh "./gradlew clean buildRpm deployRpm --info -PtargetHost=${params.TARGETHOST} -PsshUser=${username} -PsshPw=${passwd} -PinstallTarget=${params.TARGET} -PserviceName=${params.TARGET} -Pversion=${params.VERSION} -PreleaseNr=200${env.BUILD_NUMBER}"
        }
        echo "Build and Install ${params.SERVICENAME} for ${params.TARGET} on ${params.TARGETHOST} done."
   }
}



