/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.maven.publish.plugin;

import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.logging.Logger;
import org.gradle.api.plugins.ExtensionContainer;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.PluginContainer;
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin;

import com.apgsga.gradle.maven.publish.extension.ApgMavenPublishDsl;
import com.apgsga.gradle.repo.plugin.ApgCommonRepoPlugin;

@NonNullApi
public class ApgMavenPublishPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final Logger logger = project.getLogger();
		final ExtensionContainer ext = project.getExtensions();
		final PluginContainer plugins = project.getPlugins();
		logger.info("Applying Java Plugin");
		plugins.apply(JavaPlugin.class);
		logger.info("Download dependencies from maven central");
		
		logger.info("Applying Apg Common Repo Plugin");
		plugins.apply(ApgCommonRepoPlugin.class);
		logger.info("Applying Maven Publish Plugin");
		plugins.apply(MavenPublishPlugin.class);
		ext.create("apgMavenPublish", ApgMavenPublishDsl.class, project);
	}
}