/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.publish;

import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.ExtensionContainer;

import com.apgsga.gradle.publish.extension.ApgPublishConfig;
import com.apgsga.gradle.publish.tasks.ApgPublishTask;

@NonNullApi
public class ApgPublishPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final ExtensionContainer ext = project.getExtensions();
		ext.create("apgPublishConfig", ApgPublishConfig.class, project);
		project.getTasks().create("apgPublish", ApgPublishTask.class);
	}
}