version: '3'
services:
  server1:
    image: sshtestdebian
    build: .
    networks:
      - sshtestdebian
    ports:
      - "2201:22"

  server2:
    image: sshtestdebian
    build: .
    networks:
      - sshtestdebian
    ports:
      - "2202:22"

networks:
  sshtestdebian: