version: '3'
services:
  server1:
    image: sshtest
    container_name: jadas-1
    build: .
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - sshtest
    ports:
      - "2201:22"

  server2:
    image: sshtest
    container_name: jadas-2
    build: .
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - sshtest
    ports:
      - "2202:22"

networks:
  sshtest: