version: '3'
services:
  server1:
    image: sshtest
    build: .
    networks:
      - sshtest
    ports:
      - "2201:22"

  server2:
    image: sshtest
    build: .
    networks:
      - sshtest
    ports:
      - "2202:22"

networks:
  sshtest: