/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.publish.plugin;

import com.apgsga.gradle.publish.extension.ApgGenericPublish;
import com.apgsga.gradle.publish.tasks.ApgPublishTask;
import net.linguica.gradle.maven.settings.MavenSettingsPlugin;
import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.logging.Logger;
import org.gradle.api.plugins.ExtensionContainer;
import org.gradle.api.plugins.PluginContainer;

@NonNullApi
public class ApgPublishPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final ExtensionContainer ext = project.getExtensions();
		final Logger logger = project.getLogger();
		final PluginContainer plugins = project.getPlugins();
		ApgGenericPublish extension = ext.create("apgGenericPublishConfig", ApgGenericPublish.class, project);
		logger.info("Applying Apg Common Repo Plugin");
		plugins.apply(MavenSettingsPlugin.class);
		ApgPublishTask publishTask = project.getTasks().create("apgGenericPublish", ApgPublishTask.class);
		publishTask.setArtefactFile(extension.getArtefactFileProvider());

	}
}