/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.mavenpublish;

import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.logging.Logger;
import org.gradle.api.plugins.ExtensionContainer;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.PluginContainer;
import org.gradle.api.publish.maven.plugins.MavenPublishPlugin;

@NonNullApi
public class ApgMavenPublishPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final Logger logger = project.getLogger();
		final ExtensionContainer ext = project.getExtensions();
		final PluginContainer plugins = project.getPlugins();
		logger.info("Applying Java Plugin");
		plugins.apply(JavaPlugin.class);
		logger.info("Download dependencies from maven central");
		
		// TODO (CHE, 11.9) Externalize this 
		project.getRepositories().mavenCentral();
		logger.info("Applying Maven Publish Plugin");
		plugins.apply(MavenPublishPlugin.class);
		ext.create("apgMavenPublishConfig", ApgMavenPublishDsl.class, project);
	}
}