
parameters {
   string(name: 'modules', defaultValue: '', description: 'Modules to Build')
}
modules = "${params.modules}".split(':')
pipeline {

    agent any
    stages {
          stage('Maven Builds') {
              steps {
                maven_build(modules)
              }
          }
          stage('Package') {
              steps {
                 pkg('testapp-pkg')
              }
          }
     }
}


def maven_build(list) {
    list.each { module ->
        dir("${module}") {
            sh "mvn clean install"
         }
    }
}

def pkg(packagename) {
    dir ("${packagename}") {
        sh "chmod +x gradlew"
        sh "./gradlew clean buildRpm --info  --stacktrace -Pversion=1.0 -PreleaseNr=12"
    }
}