
parameters {
   string(name: 'modules', defaultValue: '', description: 'Modules to Build')
}
modules = "${params.modules}".split(':')
pipeline {

    agent any
    stages {
          stage('Maven Builds') {
              steps {
                maven_build(modules)
              }
          }
     }
}


def maven_build(list) {
    list.each { module ->
        dir("${module}") {
            sh "mvn clean install"
         }
    }
}