
parameters {
    string(name: 'TARGET', defaultValue: 'CHEI212', description: 'Installations Target')
    string(name: 'VERSION', defaultValue: '0.1-SNAPSHOT', description: 'Version Nummer')
    string(name: 'SERVICENAME', defaultValue: 'echoservice', description: 'Name of Service')
    string(name: 'TARGETHOST', defaultValue: 'jades-e.apgsga.ch', description: 'DSN Name of Targethost')
    string(name: 'REPO' , defaultValue: 'https://github.com/apgsga-it/apg-gradle-plugins.git', description: 'VCS Repo of module')
    string(name: 'MODULE' , defaultValue: 'testapp-pkg', description: 'Build directory')
    string(name: 'BRANCH' , defaultValue: 'master', description: 'Branch of Module')
    string(name: 'RELEASENR' , defaultValue: '1', description: 'Release Nr of Rpm')
    
}

stage("Build and Install ${params.SERVICENAME} for ${params.TARGET} on ${params.TARGETHOST}") {
 node {
		checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: "${params.BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${params.REPO}"]]]        
		dir ("${params.MODULE}") {
			sh "chmod +x ./gradlew"
    		withCredentials([usernamePassword(credentialsId:'jadas-e-ssh', passwordVariable: 'passwd', usernameVariable: 'username')])   { 
    		    def cmd = "./gradlew clean buildRpm deployRpm --info -PsshUser=${username} -PsshPw=${passwd}"
    		    def cmdWithParameter = "${cmd} -PtargetHost=${params.TARGETHOST} -PinstallTarget=${params.TARGET} -PserviceName=${params.TARGET}" 
    		    def cmdToExec = "${cmdWithParameter} -PserviceName=${params.SERVICENAME}  -PserviceVersion=${params.VERSION} -PreleaseNr=${params.RELEASENR}"
    		    echo cmdToExec.toString()
            	sh cmdToExec

			}
      }
      echo "Build and Install ${params.SERVICENAME} for ${params.TARGET} on ${params.TARGETHOST} done."
   }
}



