/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.repo.plugin;

import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.ExtensionContainer;

import com.apgsga.gradle.repo.extensions.LocalRepo;
import com.apgsga.gradle.repo.extensions.RemoteRepo;


@NonNullApi
public class ApgCommonRepoPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final ExtensionContainer ext = project.getExtensions();
		ext.create("apgArtifactoryRepo", RemoteRepo.class, project);
		ext.create("apgLocalRepo", LocalRepo.class, project);
	}
}