/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apgsga.gradle.rpmpublish;

import org.gradle.api.NonNullApi;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.ExtensionContainer;

import com.apgsga.gradle.rpmpublish.tasks.ApgRpmPublishTask;

@NonNullApi
public class ApgRpmPublishPlugin implements Plugin<Project> {

	@Override
	public void apply(final Project project) {
		final ExtensionContainer ext = project.getExtensions();
		ext.create("apgRpmPublishConfig", ApgRpmPublishConfig.class, project);
		project.getTasks().create("apgRpmPublish", ApgRpmPublishTask.class);
	}
}